SELECT
  S.SIM SIM
, S.STOCK_KIT KIT
, S.BRICK BRICK
, S.BOX BOX
, S.PALLET PALLET
, S.INSERT_DT INSERT_DT
, S.BATCH_DT BATCH_DT
FROM
  ((
   SELECT *
   FROM
     AGGR.COMMISSIONS_DIM_SIM_DETAILS
   WHERE tbl_dt ={table_dt}
)  S
INNER JOIN (
   SELECT C.PPMS_FIRST_KITSIM
   FROM
     (AGGR.SUBSCRIBER_BASE C
   INNER JOIN "I_COMMS".dim_trade_partner_location TPS ON (C.SHIP_TO_SITE_USE_ID = TPS.TRADE_PARTNER_STORE_ID))
   WHERE ((C.TBL_DT = {table_dt} AND (TPS.TRADE_PARTNER_TYPE IS NOT NULL)) AND (COMMISSIONABLE_ACTIVATION_DT >= cast(date_format(date_parse('{table_dt}','%Y%m%d') - interval '29' day,'%Y%m%d') as int)))
   GROUP BY C.PPMS_FIRST_KITSIM
)  SB ON (S.SIM = SB.PPMS_FIRST_KITSIM))
