SELECT
  CAST(TRADE_PARTNER_STORE_ID AS bigint) TRADE_PARTNER_STORE_ID
, TRADE_PARTNER_NAME
, SDEALER
, TRADE_PARTNER_STORE
, CUSTOMER_CATEGORY_CODE
, DEMAND_CLASS_CODE
, PROVINCE
, CITY
, REGION
, CHANNEL_TYPE
, TRADE_PARTNER_TYPE
, (CASE WHEN (TRADE_PARTNER_TYPE = 'BRANDED') THEN (CASE WHEN (DEMAND_CLASS_CODE LIKE '%NON%OWNED%') THEN 'NON OWNED' WHEN (DEMAND_CLASS_CODE LIKE 'OWNED%') THEN 'OWNED' ELSE 'OTHERS' END) WHEN (TRADE_PARTNER_TYPE = 'WHOLESALERS') THEN (CASE WHEN (DI.DOMAIN_TYPE = 'DIRECT') THEN 'DIRECT' ELSE 'INDIRECT' END) ELSE TRADE_PARTNER_TYPE END) TRADE_PARTNER_SUBTYPE
, "date_format"(current_date, '%d/%m/%Y') INSERT_DT
, date_format(date_parse('{table_dt}','%Y%m%d'), '%d/%m/%Y') BATCH_DT
FROM
  ((
   SELECT
     SITE_USE_ID TRADE_PARTNER_STORE_ID
   , "upper"(PRIMARY_GROUP) TRADE_PARTNER_NAME
   , SDEALER
   , STORE TRADE_PARTNER_STORE
   , CUSTOMER_CATEGORY_CODE
   , "upper"(DEMAND_CLASS_CODE) DEMAND_CLASS_CODE
   , PROVINCE
   , CITY
   , REGION_NAME REGION
   , DEMAND_CATEGORY CHANNEL_TYPE
   , D.DOMAIN_DESCRIPTION TRADE_PARTNER_TYPE
   , 'ERP' SOURCE_TYPE
   , current_date INSERT_DT
   , DATE '9999-12-31' BATCH_DT
   FROM
     ("AR_SUBSCRIBER_C2"."DIM_CHANNEL_SITE_ID" C
   INNER JOIN aggr."DOMAIN_IDENTITY" D ON (D.DOMAIN_CODE = C.CUSTOMER_CATEGORY_CODE))
   WHERE ((D.DOMAIN_PARENT IS NULL) AND (D.DOMAIN_TYPE = 'TRADE PARTNER'))
UNION ALL    SELECT
     SITE_USE_ID TRADE_PARTNER_STORE_ID
   , "upper"(PRIMARY_GROUP) TRADE_PARTNER_NAME
   , SDEALER
   , STORE TRADE_PARTNER_STORE
   , CUSTOMER_CATEGORY_CODE
   , "upper"(DEMAND_CLASS_CODE) DEMAND_CLASS_CODE
   , PROVINCE
   , CITY
   , REGION_NAME REGION
   , DEMAND_CATEGORY CHANNEL_TYPE
   , DOMAIN_DESCRIPTION TRADE_PARTNER_TYPE
   , 'ERP' SOURCE_TYPE
   , current_date INSERT_DT
   , DATE '9999-12-31' BATCH_DT
   FROM
     ("AR_SUBSCRIBER_C2"."DIM_CHANNEL_SITE_ID" C
   INNER JOIN aggr."DOMAIN_IDENTITY" D ON (D.DOMAIN_CODE = C.CUSTOMER_CATEGORY_CODE))
   WHERE (("regexp_like"("upper"(PRIMARY_GROUP), D.DOMAIN_PARENT) AND (DOMAIN_PARENT IS NOT NULL)) AND (D.DOMAIN_TYPE = 'TRADE PARTNER'))
UNION ALL    SELECT
     (-1 * CAST(DOMAIN_CODE AS int)) SITE_USE_ID
   , "upper"("substring"(DOMAIN_DESCRIPTION, 1, ("strpos"(DOMAIN_DESCRIPTION, '-', 1) - 1))) TRADE_PARTNER_NAME
   , null SDEALER
   , 'N/A' TRADE_PARTNER_STORE
   , 'WHOLESALERS' CUSTOMER_CATEGORY_CODE
   , 'WHOLESALERS' DEMAND_CLASS_CODE
   , "substring"(DOMAIN_DESCRIPTION, ("strpos"(DOMAIN_DESCRIPTION, '-', 1) + 2), (("strpos"(DOMAIN_DESCRIPTION, '(', -1) - "strpos"(DOMAIN_DESCRIPTION, '-', 1)) - 3)) PROVINCE
   , null CITY
   , "substring"(DOMAIN_DESCRIPTION, ("strpos"(DOMAIN_DESCRIPTION, '-', 1) + 2), (("strpos"(DOMAIN_DESCRIPTION, '(', -1) - "strpos"(DOMAIN_DESCRIPTION, '-', 1)) - 3)) REGION
   , 'INFORMAL DIRECT' CHANNEL_TYPE
   , 'WHOLESALERS' TRADE_PARTNER_TYPE
   , 'ERS' SOURCE_TYPE
   , current_date INSERT_DT
   , DATE '9999-12-31' BATCH_DT
   FROM
     aggr."DOMAIN_IDENTITY"
   WHERE (DOMAIN_TYPE = 'ERS')
UNION ALL    SELECT
     (SITE_USE_ID * 1000) TRADE_PARTNER_STORE_ID
   , PRIMARY_GROUP TRADE_PARTNER_NAME
   , SDEALER
   , STORE TRADE_PARTNER_STORE
   , CUSTOMER_CATEGORY_CODE
   , DEMAND_CLASS_CODE
   , PROVINCE
   , CITY
   , REGION_NAME REGION
   , DEMAND_CATEGORY CHANNEL_TYPE
   , 'WHOLESALERS' TRADE_PARTNER_TYPE
   , 'MANUAL' SOURCE_TYPE
   , current_date INSERT_DT
   , DATE '9999-12-31' BATCH_DT
   FROM
     "AR_SUBSCRIBER_C2"."DIM_CHANNEL_SITE_ID" C
   WHERE (SITE_USE_ID IN (SELECT COALESCE(ORIGINAL_SITE_USE_ID, DECIMAL '0.0')
FROM
  ("AGGR"."BLUE_LABEL_WHOLESALER_BASE" BL
INNER JOIN (
   SELECT
     MSISDN
   , PPMS_FIRST_KITSIM
   FROM
     aggr."SUBSCRIBER_BASE"
   WHERE (tbl_dt ={table_dt})
)  SB ON ((BL.MSISDN_KEY = SB.MSISDN) AND (BL.SIM = SB.PPMS_FIRST_KITSIM)))
))
)  T
LEFT JOIN aggr."DOMAIN_IDENTITY" DI ON ("regexp_like"(T.TRADE_PARTNER_NAME, DI.DOMAIN_CODE) AND (DI.DOMAIN_TYPE = 'DIRECT')))