SELECT
    INVENTORY_ITEM_ID,
    CATEGORY_SET_NAME,
    CAT_SEGMENT1,
    CAT_SEGMENT2,
    CAT_SEGMENT3,
    CAT_SEGMENT4,
    CAT_SEGMENT5,
    CAT_SEGMENT6,
    CAT_DESCRIPTION,
    DESCRIPTION,
    SEGMENT1,
    INSERT_DT,
    BATCH_DT
FROM i_comms.DIM_INVENTORY_ITEMS